#!/bin/bash

docker tag $IMAGE_NAME-aarch64 $DOCKER_REPO-aarch64:$DOCKER_TAG
docker push $DOCKER_REPO-aarch64:$DOCKER_TAG

docker tag $IMAGE_NAME-armhf $DOCKER_REPO-armhf:$DOCKER_TAG
docker push $DOCKER_REPO-armhf:$DOCKER_TAG
