#!/usr/bin/with-contenv bash

# Change configuration
> /etc/minidlna.conf
for VAR in $(env); do
  if [[ "$VAR" =~ ^MINIDLNA_ ]]; then
    minidlna_name=$(echo "$VAR" | sed -r "s/MINIDLNA_(.*)=.*/\1/g" | tr '[:upper:]' '[:lower:]')
    minidlna_value=$(echo "$VAR" | sed -r "s/.*=(.*)/\1/g")
    echo "${minidlna_name}=${minidlna_value}" >> /etc/minidlna.conf
  fi
done

mkdir /data/thumbnails
mkdir /data/workdir
mount -t overlay overlay -o lowerdir=/media,upperdir=/data/thumbnails,workdir=/data/workdir /media
chmod +x /thumbnails.sh
/thumbnails.sh