#!/usr/bin/with-contenv bash

# Change configuration
: > /etc/minidlna.conf
for VAR in $(env); do
  if [[ "$VAR" =~ ^MINIDLNA_ ]]; then
    minidlna_value=$(echo "$VAR" | sed -r "s/.*=(.*)/\\1/g")
    # Support multi media dirs
    if [[ "$VAR" =~ ^MINIDLNA_media_dir ]]; then
      minidlna_name='media_dir'
    else
      minidlna_name=$(echo "$VAR" | sed -r "s/MINIDLNA_(.*)=.*/\\1/g" | tr '[:upper:]' '[:lower:]')
    fi
    echo "${minidlna_name}=${minidlna_value}" >> /etc/minidlna.conf
  fi
done

echo "db_dir=/db/minidlna" >> /etc/minidlna.conf